#!/bin/bash

email=$1
pass=$2

#Get wireles interface name
wlan=$(iwconfig | grep "IEEE")
for x in {1..5}
do
  wlan=${wlan%IEEE*}
  wlan="${wlan//+([[:space:]])/}"
done

sendEmail() {
  #Get ip address
  ip=$( ifconfig | grep "inet addr:" )
  ip=${ip:50}
  ip="${ip//+([[:space:]])/}"
  #Get essid of network connected to
  essid=$( iwconfig | grep "ESSID:" )
  essid=${essid#*ESSID:}
  essid="${essid//+([[:space:]])/}"
  #Get ssh status
  sshStatus=$(service ssh status | grep "Active:")
  sshStatus="SSH "$sshStatus
  sshStatus="${sshStatus//+([[:space:]])/}"
  #Send the email
  echo "import smtplib" > tmpSend.py
  emailProvider=${email#*@}
  emailProvider=${emailProvider%.*}
  emailhub=$( cat MailServers | grep "$emailProvider" )
  mailhub="${mailhub//+([[:space:]])/}"
  server=${mailhub#*:}
  port=${mailhub%:*}
  echo "server=smtplib.SMTP('$server',$port)" >> tmpSend.py
  echo "server.starttls()" >> tmpSend.py
  echo "server.login('$email','$pass')" >> tmpSend.py
  echo "msg='$wlan\n$ip\n$essid\n$sshStatus'" >> tmpSend.py
  echo "server.sendmail('$email','$email',msg)" >> tmpSend.py
  echo "server.quit()" >> tmpSend.py
  chmod +x tmpSend.py
  sudo python2 tmpSend.py
}
#Create open network
startAP() {
  sudo ifconfig $wlan down
  cd create_ap
  sudo create_ap -n $wlan PocketPi
}

#Check if pi is connected to the internet
if ping -c 1 8.8.8.8 &> /dev/null
then
  sendEmail
else
  startAP
fi
