#!/bin/bash

#Get wireles interface name
wlan=$(iwconfig | grep "IEEE")
for x in {1..5}
do
  wlan=${wlan%IEEE*}
done

sendEmail() {
  #Get ip address
  ip=$( ifconfig | grep "inet addr:" )
  ip=${ip:50}
  #Get essid of network connected to
  essid=$( iwconfig | grep "ESSID:" )
  essid=${essid#*ESSID:}
  #Get ssh status
  sshStatus=$(service ssh status | grep "Active:")
  sshStatus="SSH "$sshStatus
  #Send the email
  echo "$wlan\n$ip\n$essid\n$sshStatus" | mail -s "PocketPi $(hostname)" $email
}
#Create open network
startAP() {
  sudo ifconfig $wlan down
  cd create_ap
  sudo create_ap -n $wlan PocketPi
}

#Check if pi is connected to the internet
if ping -c 1 8.8.8.8 &> /dev/null
then
  sendEmail
else
  startAP
fi
