#!/bin/bash

email=$1
pass=$2

#Get wireles interface name
wlan=$(iwconfig | grep "IEEE")
for x in {1..5}
do
  wlan=${wlan%IEEE*}
done

strindex(){
  x="${1%%$2*}"
  [[ "$x" = "$1" ]] && return -1 || return "${#x}"
}

sendEmail() {
  #Get ip address
  ip=$( ifconfig | grep "inet " )
  ip=${ip#*255.0.0.0}
  ip=${ip% inet*}
  #Get essid of network connected to
  essid=$( iwconfig | grep "ESSID:" )
  essid=${essid#*ESSID:}
  essid=${essid#*'"'}
  essid=${essid%'IEEE'*}
  essid=${essid%'" '*}
  #Get ssh status
  sshStatus=$(service ssh status | grep "Active:")
  sshStatus="SSH"$sshStatus
  len=${#wlan}
  wlan=${wlan:0:$len-5}
  #Send the email
  sudo echo "import smtplib" > tmpSend.py
  emailProvider=${email#*@}
  emailProvider=${emailProvider%.*}
  emailhub=$( cat MailServers | grep "$emailProvider" )
  port=${emailhub#*:}
  server=${emailhub%:*}
  sudo echo "server=smtplib.SMTP('$server',$port)" >> tmpSend.py
  sudo echo "server.starttls()" >> tmpSend.py
  sudo echo "server.login('$email','$pass')" >> tmpSend.py
  ip=${ip#*i}
  ip="i"$ip
  ip=${ip%Bcast*}
  len=${#ip}
  ip=${ip:0:$len-1}
  sudo echo "msg='\nNetwork adapter: $wlan\n$ip\nConnected Network: $essid\n$sshStatus'" >> tmpSend.py
  sudo echo "server.sendmail('$email','$email',msg)" >> tmpSend.py
  sudo echo "server.quit()" >> tmpSend.py
  chmod +x tmpSend.py
  sudo python2 tmpSend.py
  sudo rm tmpSend.py
}
#Create open network
startAP() {
  sudo ifconfig $wlan down
  cd create_ap
  sudo create_ap -n $wlan PocketPi
}

#Check if pi is connected to the internet
if ping -c 1 8.8.8.8 &> /dev/null
then
  sendEmail
else
  startAP
fi
